name: Tests & Coding Standards
'on':
  pull_request:
    branches:
      - 'dev'
      - 'main'
jobs:
  test:
    name: Run Tests & Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run test
      - run: npm run build